version: '3.3'
services:
  web:
       image: php:7.3-apache
#       container_name: php73
       build:
            context: ./dockerfiles
            dockerfile: php73.docker
       volumes:
          - ./html:/var/www/html
          - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
       links:
       - "db:database"
       ports:
          - 81
       environment:
         WWWUSER: borapedi
         WWWGROUP: borapedi    
       depends_on:
         - db
#         - nginx
  db:
    container_name: db
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: #
      MYSQL_DATABASE: #
      MYSQL_USER: #
      MYSQL_PASSWORD: #
    ports:
     - "3306:3306"
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 7000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
     - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  portainer:
    container_name: portainer
    entrypoint:
      - /portainer
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    image: cr.portainer.io/portainer/portainer-ce:2.9.3
    ipc: private
    logging:
      driver: json-file
      options: {}
    ports:
      - 8000:8000/tcp
      - 9442:9443/tcp
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/portainer_data/data
    working_dir: /
  rabbitmq:
   image: "rabbitmq:3-management"
   ports:
    - "5672:5672"
    - "15672:15672"
   volumes:
    - "rabbitmq_data:/data"
volumes:
    rabbitmq_data:
    portainer_data:
     driver: local
